# pytorch_lightning==2.5.2
trainer:
  limit_train_batches: &data_radio .04
  limit_val_batches: *data_radio
  limit_test_batches: *data_radio
  limit_predict_batches: *data_radio
  log_every_n_steps: 1
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: tb_logs
      name: null
      flush_secs: 20
  callbacks: _shared.TensorBoardLauncher
# model:
  # learning_rate: 0.02
